services:
  web:
    build: .
    volumes:
      - "./:/var/www/html/"
    ports:
    - 8080:80
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 12345
    ports:
    - 3306:3306
