services:
  web:
    build: .
    volumes:
      - "./:/var/www/html/"
    ports:
    - 8080:80
  db:
    image: mariadb
    restart: always
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      MARIADB_ROOT_USER: root
      MARIADB_ROOT_PASSWORD: 123456
      MARIADB_USER: user
      MARIADB_PASSWORD: 123456
      MYSQL_ROOT_HOST: "%"
      MARIADB_ROOT_HOST: "%"

    ports:
    - 3306:3306
